name: Deploy Supabase Edge Functions

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - production
        required: true

jobs:
  functions-deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    concurrency: ${{ inputs.environment }}
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Are there functions to deploy?
        id: exists
        run: |
          if [ ! -d "supabase/functions" ] || [ -z "$(ls -A supabase/functions)" ]; then
            echo "There are no functions to deploy."
            gh run cancel ${{ github.run_id }}
            gh run watch ${{ github.run_id }}
            exit 0
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: "Install Supabase CLI"
        run: npm ci -w supabase
      - name: "Link Supabase project."
        run: npx supabase link --project-ref ${{ vars.SUPABASE_PROJECT_ID }}
      - name: "Deploy edge functions."
        run: npx supabase functions deploy
